name: Auto Merge PRs

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

jobs:
  auto-merge:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.7

    - name: Auto merge
      if: github.event.pull_request.merged == false && github.event.pull_request.state == 'open'
      run: |
        git config --global user.name "kokodak"
        git config --global user.email "kokodakadokok@gmail.com"
        gh pr merge ${{ github.event.pull_request.number }} --merge --auto --admin
      env:
        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}
