name: Update README on Issue

on:
  issues:
    types: [opened]

jobs:
  comment-on-issue:
    runs-on: ubuntu-latest
    steps:
    - name: Comment on the issue
      run: |
        response=$(curl -X POST -H "Authorization: token ${{ secrets.MY_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/comments \
          -d '{"body": "Hi! This is kokodak Bot. Please wait a moment, your guestbook comment is being registered."}')
        echo "response=$response"
        comment_id=$(echo "$response" | jq -r '.id')
        echo "COMMENT_ID=$comment_id" >> $GITHUB_ENV
    
  update-readme:
    runs-on: ubuntu-latest
    needs: comment-on-issue
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Update README.md
      run: |
        echo "${{ github.event.issue.body }}  \`comment by ${{ github.event.issue.user.login }}\`" >> README.md
        echo "" >> README.md

    - name: Commit changes
      run: |
        git config --global user.name "kokodak"
        git config --global user.email "kokodakadokok@gmail.com"
        git add README.md
        git commit -m "Update Guestbook with #${{ github.event.issue.number }}"

    - name: Push changes
      uses: ad-m/github-push-action@v0.8.0
      with:
        github_token: ${{ secrets.MY_TOKEN }}

  update-comment:
    runs-on: ubuntu-latest
    needs: update-readme
    steps:
    - name: Update issue comment
      run: |
        if [ -n "$COMMENT_ID" ]; then
          echo "Updating comment with ID: $COMMENT_ID"
          curl -X PATCH -H "Authorization: token ${{ secrets.MY_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/issues/comments/$COMMENT_ID \
            -d '{"body": "Thank you for your contribution!"}'
        else
          echo "Comment ID not found. Skipping update."
        fi

  close-issue:
    runs-on: ubuntu-latest
    needs: update-comment
    steps:
    - name: Close the issue
      run: |
        curl -X PATCH -H "Authorization: token ${{ secrets.MY_TOKEN }}" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }} \
          -d '{"state": "closed"}'
